# Generated by Django 6.0.4 on 2026-04-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='is_scrambled',
            field=models.BooleanField(default=False),
        ),
    ]
