# Generated by Django 6.0.4 on 2026-04-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_imageupload_is_scrambled'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='grid_cols',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='grid_rows',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/refs/'),
        ),
    ]
